Feature add form
alexeionline/bssp pull request #14
Opened 2018-08-18 08:42 UTC by xKnowledgeless

2018-08-18 09:05 UTC, alexeionline requested changes

2018-08-18 09:05 UTC, alexeionline commented on src/actions/objects.js
> +
export const addNewObjectFromForm = () => ({ type: ADD_OBJECT_FROM_FORM });

2018-08-18 09:05 UTC, alexeionline commented on src/actions/objects.js
> +
можешь писать меньше букв

2018-08-18 09:05 UTC, alexeionline commented on src/actions/objects.js
> +export const changeNewObjectFromForm = (inputType, inputValue) => {
const payload = {
    inputType,
    inputValue
  };

2018-08-18 09:05 UTC, alexeionline commented on src/actions/objects.js
> +export const changeNewObjectFromForm = (inputType, inputValue) => {
тоже меньше букв

2018-08-18 09:05 UTC, alexeionline commented on src/components/Add.js
> +      const coords = result.geoObjects.get(0).geometry.getCoordinates();
const [lat, lon] = result.geoObjects.get(0).geometry.getCoordinates();

2018-08-18 09:05 UTC, alexeionline commented on src/components/Add.js
> +  const changeCoordinates = (name, value, geocodeController) => {
const changeCoordinates = (name, value, { city, address}) => {

2018-08-18 09:05 UTC, alexeionline commented on src/components/Add.js
> +    const mapCoords = event.get("target").geometry.getCoordinates();
const [ lat, lon ] = event.get("target").geometry.getCoordinates();

2018-08-18 09:05 UTC, alexeionline commented on src/components/Add.js
> +            value={newObject.map && newObject.map[0]}
newObject.map && newObject.map[0] - вынеси это выражение выше, а сюда передай уже однозначное значение

2023-05-28 21:19 UTC, kpodmasko commented
пожалуй закрою)

2023-05-28 21:19 UTC, closed without merging